// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) import OpenAPIRuntime
#if os(Linux)
@preconcurrency import struct Foundation.URL
@preconcurrency import struct Foundation.Data
@preconcurrency import struct Foundation.Date
#else
import struct Foundation.URL
import struct Foundation.Data
import struct Foundation.Date
#endif
import HTTPTypes
extension APIProtocol {
    /// Registers each operation handler with the provided transport.
    /// - Parameters:
    ///   - transport: A transport to which to register the operation handlers.
    ///   - serverURL: A URL used to determine the path prefix for registered
    ///   request handlers.
    ///   - configuration: A set of configuration values for the server.
    ///   - middlewares: A list of middlewares to call before the handler.
    public func registerHandlers(
        on transport: any ServerTransport,
        serverURL: Foundation.URL = .defaultOpenAPIServerURL,
        configuration: Configuration = .init(),
        middlewares: [any ServerMiddleware] = []
    ) throws {
        let server = UniversalServer(
            serverURL: serverURL,
            handler: self,
            configuration: configuration,
            middlewares: middlewares
        )
        try transport.register(
            {
                try await server.postRoomCreate(
                    request: $0,
                    body: $1,
                    metadata: $2
                )
            },
            method: .post,
            path: server.apiPathComponentsWithServerPrefix("/room/create")
        )
        try transport.register(
            {
                try await server.getRoomInfoCode(
                    request: $0,
                    body: $1,
                    metadata: $2
                )
            },
            method: .get,
            path: server.apiPathComponentsWithServerPrefix("/room/info/{code}")
        )
        try transport.register(
            {
                try await server.postRoomJoinCode(
                    request: $0,
                    body: $1,
                    metadata: $2
                )
            },
            method: .post,
            path: server.apiPathComponentsWithServerPrefix("/room/join/{code}")
        )
        try transport.register(
            {
                try await server.getRoomJoinRequestsCode(
                    request: $0,
                    body: $1,
                    metadata: $2
                )
            },
            method: .get,
            path: server.apiPathComponentsWithServerPrefix("/room/join-requests/{code}")
        )
        try transport.register(
            {
                try await server.postRoomJoinRequestsCode(
                    request: $0,
                    body: $1,
                    metadata: $2
                )
            },
            method: .post,
            path: server.apiPathComponentsWithServerPrefix("/room/join-requests/{code}")
        )
        try transport.register(
            {
                try await server.getRoomQuestionCode(
                    request: $0,
                    body: $1,
                    metadata: $2
                )
            },
            method: .get,
            path: server.apiPathComponentsWithServerPrefix("/room/question/{code}")
        )
        try transport.register(
            {
                try await server.postRoomQuestionCode(
                    request: $0,
                    body: $1,
                    metadata: $2
                )
            },
            method: .post,
            path: server.apiPathComponentsWithServerPrefix("/room/question/{code}")
        )
        try transport.register(
            {
                try await server.putRoomQuestionCodeQuestionID(
                    request: $0,
                    body: $1,
                    metadata: $2
                )
            },
            method: .put,
            path: server.apiPathComponentsWithServerPrefix("/room/question/{code}/{questionID}")
        )
        try transport.register(
            {
                try await server.deleteRoomQuestionCodeQuestionID(
                    request: $0,
                    body: $1,
                    metadata: $2
                )
            },
            method: .delete,
            path: server.apiPathComponentsWithServerPrefix("/room/question/{code}/{questionID}")
        )
        try transport.register(
            {
                try await server.postRoomVoteCodeQuestionID(
                    request: $0,
                    body: $1,
                    metadata: $2
                )
            },
            method: .post,
            path: server.apiPathComponentsWithServerPrefix("/room/vote/{code}/{questionID}")
        )
        try transport.register(
            {
                try await server.getRoomQuestionResultCodeQuestionID(
                    request: $0,
                    body: $1,
                    metadata: $2
                )
            },
            method: .get,
            path: server.apiPathComponentsWithServerPrefix("/room/question-result/{code}/{questionID}")
        )
        try transport.register(
            {
                try await server.getRoomQuestionVoteCountCodeQuestionID(
                    request: $0,
                    body: $1,
                    metadata: $2
                )
            },
            method: .get,
            path: server.apiPathComponentsWithServerPrefix("/room/question-vote-count/{code}/{questionID}")
        )
    }
}

fileprivate extension UniversalServer where APIHandler: APIProtocol {
    /// Creates a new room
    ///
    /// Creates a new room with the given options.
    ///
    /// - Remark: HTTP `POST /room/create`.
    /// - Remark: Generated from `#/paths//room/create/post`.
    func postRoomCreate(
        request: HTTPTypes.HTTPRequest,
        body: OpenAPIRuntime.HTTPBody?,
        metadata: OpenAPIRuntime.ServerRequestMetadata
    ) async throws -> (HTTPTypes.HTTPResponse, OpenAPIRuntime.HTTPBody?) {
        try await handle(
            request: request,
            requestBody: body,
            metadata: metadata,
            forOperation: Operations.PostRoomCreate.id,
            using: {
                APIHandler.postRoomCreate($0)
            },
            deserializer: { request, requestBody, metadata in
                let headers: Operations.PostRoomCreate.Input.Headers = .init(accept: try converter.extractAcceptHeaderIfPresent(in: request.headerFields))
                let contentType = converter.extractContentTypeIfPresent(in: request.headerFields)
                let body: Operations.PostRoomCreate.Input.Body
                let chosenContentType = try converter.bestContentType(
                    received: contentType,
                    options: [
                        "application/json"
                    ]
                )
                switch chosenContentType {
                case "application/json":
                    body = try await converter.getRequiredRequestBodyAsJSON(
                        Operations.PostRoomCreate.Input.Body.JsonPayload.self,
                        from: requestBody,
                        transforming: { value in
                            .json(value)
                        }
                    )
                default:
                    preconditionFailure("bestContentType chose an invalid content type.")
                }
                return Operations.PostRoomCreate.Input(
                    headers: headers,
                    body: body
                )
            },
            serializer: { output, request in
                switch output {
                case let .ok(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 200)
                    suppressMutabilityWarning(&response)
                    let body: OpenAPIRuntime.HTTPBody
                    switch value.body {
                    case let .json(value):
                        try converter.validateAcceptIfPresent(
                            "application/json",
                            in: request.headerFields
                        )
                        body = try converter.setResponseBodyAsJSON(
                            value,
                            headerFields: &response.headerFields,
                            contentType: "application/json; charset=utf-8"
                        )
                    }
                    return (response, body)
                case let .internalServerError(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 500)
                    suppressMutabilityWarning(&response)
                    let body: OpenAPIRuntime.HTTPBody
                    switch value.body {
                    case let .json(value):
                        try converter.validateAcceptIfPresent(
                            "application/json",
                            in: request.headerFields
                        )
                        body = try converter.setResponseBodyAsJSON(
                            value,
                            headerFields: &response.headerFields,
                            contentType: "application/json; charset=utf-8"
                        )
                    }
                    return (response, body)
                case let .undocumented(statusCode, _):
                    return (.init(soar_statusCode: statusCode), nil)
                }
            }
        )
    }
    /// Get information about a room
    ///
    /// Provides information about a room, like whether the room code corresponds to a valid room
    ///
    /// - Remark: HTTP `GET /room/info/{code}`.
    /// - Remark: Generated from `#/paths//room/info/{code}/get`.
    func getRoomInfoCode(
        request: HTTPTypes.HTTPRequest,
        body: OpenAPIRuntime.HTTPBody?,
        metadata: OpenAPIRuntime.ServerRequestMetadata
    ) async throws -> (HTTPTypes.HTTPResponse, OpenAPIRuntime.HTTPBody?) {
        try await handle(
            request: request,
            requestBody: body,
            metadata: metadata,
            forOperation: Operations.GetRoomInfoCode.id,
            using: {
                APIHandler.getRoomInfoCode($0)
            },
            deserializer: { request, requestBody, metadata in
                let path: Operations.GetRoomInfoCode.Input.Path = .init(code: try converter.getPathParameterAsURI(
                    in: metadata.pathParameters,
                    name: "code",
                    as: Components.Parameters.RoomCode.self
                ))
                let headers: Operations.GetRoomInfoCode.Input.Headers = .init(accept: try converter.extractAcceptHeaderIfPresent(in: request.headerFields))
                return Operations.GetRoomInfoCode.Input(
                    path: path,
                    headers: headers
                )
            },
            serializer: { output, request in
                switch output {
                case let .ok(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 200)
                    suppressMutabilityWarning(&response)
                    let body: OpenAPIRuntime.HTTPBody
                    switch value.body {
                    case let .json(value):
                        try converter.validateAcceptIfPresent(
                            "application/json",
                            in: request.headerFields
                        )
                        body = try converter.setResponseBodyAsJSON(
                            value,
                            headerFields: &response.headerFields,
                            contentType: "application/json; charset=utf-8"
                        )
                    }
                    return (response, body)
                case let .notFound(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 404)
                    suppressMutabilityWarning(&response)
                    return (response, nil)
                case let .undocumented(statusCode, _):
                    return (.init(soar_statusCode: statusCode), nil)
                }
            }
        )
    }
    /// Join a room
    ///
    /// This route only asks the room owner whether to allow you to join the room, it doesn't actually open a connection to the room. To do that, use the `/room/connect/{code}` route.
    ///
    /// - Remark: HTTP `POST /room/join/{code}`.
    /// - Remark: Generated from `#/paths//room/join/{code}/post`.
    func postRoomJoinCode(
        request: HTTPTypes.HTTPRequest,
        body: OpenAPIRuntime.HTTPBody?,
        metadata: OpenAPIRuntime.ServerRequestMetadata
    ) async throws -> (HTTPTypes.HTTPResponse, OpenAPIRuntime.HTTPBody?) {
        try await handle(
            request: request,
            requestBody: body,
            metadata: metadata,
            forOperation: Operations.PostRoomJoinCode.id,
            using: {
                APIHandler.postRoomJoinCode($0)
            },
            deserializer: { request, requestBody, metadata in
                let path: Operations.PostRoomJoinCode.Input.Path = .init(code: try converter.getPathParameterAsURI(
                    in: metadata.pathParameters,
                    name: "code",
                    as: Components.Parameters.RoomCode.self
                ))
                let headers: Operations.PostRoomJoinCode.Input.Headers = .init(accept: try converter.extractAcceptHeaderIfPresent(in: request.headerFields))
                let contentType = converter.extractContentTypeIfPresent(in: request.headerFields)
                let body: Operations.PostRoomJoinCode.Input.Body
                let chosenContentType = try converter.bestContentType(
                    received: contentType,
                    options: [
                        "application/json"
                    ]
                )
                switch chosenContentType {
                case "application/json":
                    body = try await converter.getRequiredRequestBodyAsJSON(
                        Operations.PostRoomJoinCode.Input.Body.JsonPayload.self,
                        from: requestBody,
                        transforming: { value in
                            .json(value)
                        }
                    )
                default:
                    preconditionFailure("bestContentType chose an invalid content type.")
                }
                return Operations.PostRoomJoinCode.Input(
                    path: path,
                    headers: headers,
                    body: body
                )
            },
            serializer: { output, request in
                switch output {
                case let .ok(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 200)
                    suppressMutabilityWarning(&response)
                    let body: OpenAPIRuntime.HTTPBody
                    switch value.body {
                    case let .json(value):
                        try converter.validateAcceptIfPresent(
                            "application/json",
                            in: request.headerFields
                        )
                        body = try converter.setResponseBodyAsJSON(
                            value,
                            headerFields: &response.headerFields,
                            contentType: "application/json; charset=utf-8"
                        )
                    }
                    return (response, body)
                case let .forbidden(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 403)
                    suppressMutabilityWarning(&response)
                    return (response, nil)
                case let .notFound(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 404)
                    suppressMutabilityWarning(&response)
                    return (response, nil)
                case let .undocumented(statusCode, _):
                    return (.init(soar_statusCode: statusCode), nil)
                }
            }
        )
    }
    /// Pending requests to join a room
    ///
    /// Allows an admin to view pending join requests for a room
    ///
    /// - Remark: HTTP `GET /room/join-requests/{code}`.
    /// - Remark: Generated from `#/paths//room/join-requests/{code}/get`.
    func getRoomJoinRequestsCode(
        request: HTTPTypes.HTTPRequest,
        body: OpenAPIRuntime.HTTPBody?,
        metadata: OpenAPIRuntime.ServerRequestMetadata
    ) async throws -> (HTTPTypes.HTTPResponse, OpenAPIRuntime.HTTPBody?) {
        try await handle(
            request: request,
            requestBody: body,
            metadata: metadata,
            forOperation: Operations.GetRoomJoinRequestsCode.id,
            using: {
                APIHandler.getRoomJoinRequestsCode($0)
            },
            deserializer: { request, requestBody, metadata in
                let path: Operations.GetRoomJoinRequestsCode.Input.Path = .init(code: try converter.getPathParameterAsURI(
                    in: metadata.pathParameters,
                    name: "code",
                    as: Components.Parameters.RoomCode.self
                ))
                let headers: Operations.GetRoomJoinRequestsCode.Input.Headers = .init(
                    roomAdminToken: try converter.getRequiredHeaderFieldAsURI(
                        in: request.headerFields,
                        name: "Room-Admin-Token",
                        as: Components.Parameters.AdminToken.self
                    ),
                    accept: try converter.extractAcceptHeaderIfPresent(in: request.headerFields)
                )
                return Operations.GetRoomJoinRequestsCode.Input(
                    path: path,
                    headers: headers
                )
            },
            serializer: { output, request in
                switch output {
                case let .ok(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 200)
                    suppressMutabilityWarning(&response)
                    let body: OpenAPIRuntime.HTTPBody
                    switch value.body {
                    case let .json(value):
                        try converter.validateAcceptIfPresent(
                            "application/json",
                            in: request.headerFields
                        )
                        body = try converter.setResponseBodyAsJSON(
                            value,
                            headerFields: &response.headerFields,
                            contentType: "application/json; charset=utf-8"
                        )
                    }
                    return (response, body)
                case let .forbidden(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 403)
                    suppressMutabilityWarning(&response)
                    return (response, nil)
                case let .notFound(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 404)
                    suppressMutabilityWarning(&response)
                    return (response, nil)
                case let .undocumented(statusCode, _):
                    return (.init(soar_statusCode: statusCode), nil)
                }
            }
        )
    }
    /// Handle join requests
    ///
    /// Allows a room admin to accept or reject join requests.
    ///
    /// - Remark: HTTP `POST /room/join-requests/{code}`.
    /// - Remark: Generated from `#/paths//room/join-requests/{code}/post`.
    func postRoomJoinRequestsCode(
        request: HTTPTypes.HTTPRequest,
        body: OpenAPIRuntime.HTTPBody?,
        metadata: OpenAPIRuntime.ServerRequestMetadata
    ) async throws -> (HTTPTypes.HTTPResponse, OpenAPIRuntime.HTTPBody?) {
        try await handle(
            request: request,
            requestBody: body,
            metadata: metadata,
            forOperation: Operations.PostRoomJoinRequestsCode.id,
            using: {
                APIHandler.postRoomJoinRequestsCode($0)
            },
            deserializer: { request, requestBody, metadata in
                let path: Operations.PostRoomJoinRequestsCode.Input.Path = .init(code: try converter.getPathParameterAsURI(
                    in: metadata.pathParameters,
                    name: "code",
                    as: Components.Parameters.RoomCode.self
                ))
                let headers: Operations.PostRoomJoinRequestsCode.Input.Headers = .init(
                    roomAdminToken: try converter.getRequiredHeaderFieldAsURI(
                        in: request.headerFields,
                        name: "Room-Admin-Token",
                        as: Components.Parameters.AdminToken.self
                    ),
                    accept: try converter.extractAcceptHeaderIfPresent(in: request.headerFields)
                )
                let contentType = converter.extractContentTypeIfPresent(in: request.headerFields)
                let body: Operations.PostRoomJoinRequestsCode.Input.Body
                let chosenContentType = try converter.bestContentType(
                    received: contentType,
                    options: [
                        "application/json"
                    ]
                )
                switch chosenContentType {
                case "application/json":
                    body = try await converter.getRequiredRequestBodyAsJSON(
                        Operations.PostRoomJoinRequestsCode.Input.Body.JsonPayload.self,
                        from: requestBody,
                        transforming: { value in
                            .json(value)
                        }
                    )
                default:
                    preconditionFailure("bestContentType chose an invalid content type.")
                }
                return Operations.PostRoomJoinRequestsCode.Input(
                    path: path,
                    headers: headers,
                    body: body
                )
            },
            serializer: { output, request in
                switch output {
                case let .ok(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 200)
                    suppressMutabilityWarning(&response)
                    let body: OpenAPIRuntime.HTTPBody
                    switch value.body {
                    case let .json(value):
                        try converter.validateAcceptIfPresent(
                            "application/json",
                            in: request.headerFields
                        )
                        body = try converter.setResponseBodyAsJSON(
                            value,
                            headerFields: &response.headerFields,
                            contentType: "application/json; charset=utf-8"
                        )
                    }
                    return (response, body)
                case let .badRequest(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 400)
                    suppressMutabilityWarning(&response)
                    let body: OpenAPIRuntime.HTTPBody
                    switch value.body {
                    case let .json(value):
                        try converter.validateAcceptIfPresent(
                            "application/json",
                            in: request.headerFields
                        )
                        body = try converter.setResponseBodyAsJSON(
                            value,
                            headerFields: &response.headerFields,
                            contentType: "application/json; charset=utf-8"
                        )
                    }
                    return (response, body)
                case let .forbidden(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 403)
                    suppressMutabilityWarning(&response)
                    return (response, nil)
                case let .notFound(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 404)
                    suppressMutabilityWarning(&response)
                    return (response, nil)
                case let .undocumented(statusCode, _):
                    return (.init(soar_statusCode: statusCode), nil)
                }
            }
        )
    }
    /// Get the active question
    ///
    /// - Remark: HTTP `GET /room/question/{code}`.
    /// - Remark: Generated from `#/paths//room/question/{code}/get`.
    func getRoomQuestionCode(
        request: HTTPTypes.HTTPRequest,
        body: OpenAPIRuntime.HTTPBody?,
        metadata: OpenAPIRuntime.ServerRequestMetadata
    ) async throws -> (HTTPTypes.HTTPResponse, OpenAPIRuntime.HTTPBody?) {
        try await handle(
            request: request,
            requestBody: body,
            metadata: metadata,
            forOperation: Operations.GetRoomQuestionCode.id,
            using: {
                APIHandler.getRoomQuestionCode($0)
            },
            deserializer: { request, requestBody, metadata in
                let path: Operations.GetRoomQuestionCode.Input.Path = .init(code: try converter.getPathParameterAsURI(
                    in: metadata.pathParameters,
                    name: "code",
                    as: Components.Parameters.RoomCode.self
                ))
                let headers: Operations.GetRoomQuestionCode.Input.Headers = .init(accept: try converter.extractAcceptHeaderIfPresent(in: request.headerFields))
                return Operations.GetRoomQuestionCode.Input(
                    path: path,
                    headers: headers
                )
            },
            serializer: { output, request in
                switch output {
                case let .ok(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 200)
                    suppressMutabilityWarning(&response)
                    let body: OpenAPIRuntime.HTTPBody
                    switch value.body {
                    case let .json(value):
                        try converter.validateAcceptIfPresent(
                            "application/json",
                            in: request.headerFields
                        )
                        body = try converter.setResponseBodyAsJSON(
                            value,
                            headerFields: &response.headerFields,
                            contentType: "application/json; charset=utf-8"
                        )
                    }
                    return (response, body)
                case let .badRequest(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 400)
                    suppressMutabilityWarning(&response)
                    return (response, nil)
                case let .notFound(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 404)
                    suppressMutabilityWarning(&response)
                    return (response, nil)
                case let .undocumented(statusCode, _):
                    return (.init(soar_statusCode: statusCode), nil)
                }
            }
        )
    }
    /// Submit a new question
    ///
    /// - Remark: HTTP `POST /room/question/{code}`.
    /// - Remark: Generated from `#/paths//room/question/{code}/post`.
    func postRoomQuestionCode(
        request: HTTPTypes.HTTPRequest,
        body: OpenAPIRuntime.HTTPBody?,
        metadata: OpenAPIRuntime.ServerRequestMetadata
    ) async throws -> (HTTPTypes.HTTPResponse, OpenAPIRuntime.HTTPBody?) {
        try await handle(
            request: request,
            requestBody: body,
            metadata: metadata,
            forOperation: Operations.PostRoomQuestionCode.id,
            using: {
                APIHandler.postRoomQuestionCode($0)
            },
            deserializer: { request, requestBody, metadata in
                let path: Operations.PostRoomQuestionCode.Input.Path = .init(code: try converter.getPathParameterAsURI(
                    in: metadata.pathParameters,
                    name: "code",
                    as: Components.Parameters.RoomCode.self
                ))
                let headers: Operations.PostRoomQuestionCode.Input.Headers = .init(
                    roomAdminToken: try converter.getRequiredHeaderFieldAsURI(
                        in: request.headerFields,
                        name: "Room-Admin-Token",
                        as: Components.Parameters.AdminToken.self
                    ),
                    accept: try converter.extractAcceptHeaderIfPresent(in: request.headerFields)
                )
                let contentType = converter.extractContentTypeIfPresent(in: request.headerFields)
                let body: Operations.PostRoomQuestionCode.Input.Body
                let chosenContentType = try converter.bestContentType(
                    received: contentType,
                    options: [
                        "application/json"
                    ]
                )
                switch chosenContentType {
                case "application/json":
                    body = try await converter.getRequiredRequestBodyAsJSON(
                        Components.Schemas.QuestionCreateRequest.self,
                        from: requestBody,
                        transforming: { value in
                            .json(value)
                        }
                    )
                default:
                    preconditionFailure("bestContentType chose an invalid content type.")
                }
                return Operations.PostRoomQuestionCode.Input(
                    path: path,
                    headers: headers,
                    body: body
                )
            },
            serializer: { output, request in
                switch output {
                case let .ok(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 200)
                    suppressMutabilityWarning(&response)
                    let body: OpenAPIRuntime.HTTPBody
                    switch value.body {
                    case let .json(value):
                        try converter.validateAcceptIfPresent(
                            "application/json",
                            in: request.headerFields
                        )
                        body = try converter.setResponseBodyAsJSON(
                            value,
                            headerFields: &response.headerFields,
                            contentType: "application/json; charset=utf-8"
                        )
                    }
                    return (response, body)
                case let .badRequest(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 400)
                    suppressMutabilityWarning(&response)
                    let body: OpenAPIRuntime.HTTPBody
                    switch value.body {
                    case let .json(value):
                        try converter.validateAcceptIfPresent(
                            "application/json",
                            in: request.headerFields
                        )
                        body = try converter.setResponseBodyAsJSON(
                            value,
                            headerFields: &response.headerFields,
                            contentType: "application/json; charset=utf-8"
                        )
                    }
                    return (response, body)
                case let .forbidden(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 403)
                    suppressMutabilityWarning(&response)
                    return (response, nil)
                case let .notFound(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 404)
                    suppressMutabilityWarning(&response)
                    return (response, nil)
                case let .internalServerError(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 500)
                    suppressMutabilityWarning(&response)
                    let body: OpenAPIRuntime.HTTPBody
                    switch value.body {
                    case let .json(value):
                        try converter.validateAcceptIfPresent(
                            "application/json",
                            in: request.headerFields
                        )
                        body = try converter.setResponseBodyAsJSON(
                            value,
                            headerFields: &response.headerFields,
                            contentType: "application/json; charset=utf-8"
                        )
                    }
                    return (response, body)
                case let .undocumented(statusCode, _):
                    return (.init(soar_statusCode: statusCode), nil)
                }
            }
        )
    }
    /// Edits the current question
    ///
    /// Modify attributes of the current question
    ///
    /// - Remark: HTTP `PUT /room/question/{code}/{questionID}`.
    /// - Remark: Generated from `#/paths//room/question/{code}/{questionID}/put`.
    func putRoomQuestionCodeQuestionID(
        request: HTTPTypes.HTTPRequest,
        body: OpenAPIRuntime.HTTPBody?,
        metadata: OpenAPIRuntime.ServerRequestMetadata
    ) async throws -> (HTTPTypes.HTTPResponse, OpenAPIRuntime.HTTPBody?) {
        try await handle(
            request: request,
            requestBody: body,
            metadata: metadata,
            forOperation: Operations.PutRoomQuestionCodeQuestionID.id,
            using: {
                APIHandler.putRoomQuestionCodeQuestionID($0)
            },
            deserializer: { request, requestBody, metadata in
                let path: Operations.PutRoomQuestionCodeQuestionID.Input.Path = .init(
                    code: try converter.getPathParameterAsURI(
                        in: metadata.pathParameters,
                        name: "code",
                        as: Components.Parameters.RoomCode.self
                    ),
                    questionID: try converter.getPathParameterAsURI(
                        in: metadata.pathParameters,
                        name: "questionID",
                        as: Components.Parameters.QuestionID.self
                    )
                )
                let headers: Operations.PutRoomQuestionCodeQuestionID.Input.Headers = .init(roomAdminToken: try converter.getRequiredHeaderFieldAsURI(
                    in: request.headerFields,
                    name: "Room-Admin-Token",
                    as: Components.Parameters.AdminToken.self
                ))
                let contentType = converter.extractContentTypeIfPresent(in: request.headerFields)
                let body: Operations.PutRoomQuestionCodeQuestionID.Input.Body
                let chosenContentType = try converter.bestContentType(
                    received: contentType,
                    options: [
                        "application/json"
                    ]
                )
                switch chosenContentType {
                case "application/json":
                    body = try await converter.getRequiredRequestBodyAsJSON(
                        Components.Schemas.QuestionModifyRequest.self,
                        from: requestBody,
                        transforming: { value in
                            .json(value)
                        }
                    )
                default:
                    preconditionFailure("bestContentType chose an invalid content type.")
                }
                return Operations.PutRoomQuestionCodeQuestionID.Input(
                    path: path,
                    headers: headers,
                    body: body
                )
            },
            serializer: { output, request in
                switch output {
                case let .ok(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 200)
                    suppressMutabilityWarning(&response)
                    return (response, nil)
                case let .badRequest(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 400)
                    suppressMutabilityWarning(&response)
                    return (response, nil)
                case let .forbidden(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 403)
                    suppressMutabilityWarning(&response)
                    return (response, nil)
                case let .notFound(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 404)
                    suppressMutabilityWarning(&response)
                    return (response, nil)
                case let .undocumented(statusCode, _):
                    return (.init(soar_statusCode: statusCode), nil)
                }
            }
        )
    }
    /// Removes the current question
    ///
    /// - Remark: HTTP `DELETE /room/question/{code}/{questionID}`.
    /// - Remark: Generated from `#/paths//room/question/{code}/{questionID}/delete`.
    func deleteRoomQuestionCodeQuestionID(
        request: HTTPTypes.HTTPRequest,
        body: OpenAPIRuntime.HTTPBody?,
        metadata: OpenAPIRuntime.ServerRequestMetadata
    ) async throws -> (HTTPTypes.HTTPResponse, OpenAPIRuntime.HTTPBody?) {
        try await handle(
            request: request,
            requestBody: body,
            metadata: metadata,
            forOperation: Operations.DeleteRoomQuestionCodeQuestionID.id,
            using: {
                APIHandler.deleteRoomQuestionCodeQuestionID($0)
            },
            deserializer: { request, requestBody, metadata in
                let path: Operations.DeleteRoomQuestionCodeQuestionID.Input.Path = .init(
                    code: try converter.getPathParameterAsURI(
                        in: metadata.pathParameters,
                        name: "code",
                        as: Components.Parameters.RoomCode.self
                    ),
                    questionID: try converter.getPathParameterAsURI(
                        in: metadata.pathParameters,
                        name: "questionID",
                        as: Components.Parameters.QuestionID.self
                    )
                )
                let headers: Operations.DeleteRoomQuestionCodeQuestionID.Input.Headers = .init(
                    roomAdminToken: try converter.getRequiredHeaderFieldAsURI(
                        in: request.headerFields,
                        name: "Room-Admin-Token",
                        as: Components.Parameters.AdminToken.self
                    ),
                    accept: try converter.extractAcceptHeaderIfPresent(in: request.headerFields)
                )
                return Operations.DeleteRoomQuestionCodeQuestionID.Input(
                    path: path,
                    headers: headers
                )
            },
            serializer: { output, request in
                switch output {
                case let .ok(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 200)
                    suppressMutabilityWarning(&response)
                    let body: OpenAPIRuntime.HTTPBody
                    switch value.body {
                    case let .json(value):
                        try converter.validateAcceptIfPresent(
                            "application/json",
                            in: request.headerFields
                        )
                        body = try converter.setResponseBodyAsJSON(
                            value,
                            headerFields: &response.headerFields,
                            contentType: "application/json; charset=utf-8"
                        )
                    }
                    return (response, body)
                case let .badRequest(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 400)
                    suppressMutabilityWarning(&response)
                    return (response, nil)
                case let .forbidden(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 403)
                    suppressMutabilityWarning(&response)
                    return (response, nil)
                case let .notFound(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 404)
                    suppressMutabilityWarning(&response)
                    return (response, nil)
                case let .undocumented(statusCode, _):
                    return (.init(soar_statusCode: statusCode), nil)
                }
            }
        )
    }
    /// Vote on a question
    ///
    /// - Remark: HTTP `POST /room/vote/{code}/{questionID}`.
    /// - Remark: Generated from `#/paths//room/vote/{code}/{questionID}/post`.
    func postRoomVoteCodeQuestionID(
        request: HTTPTypes.HTTPRequest,
        body: OpenAPIRuntime.HTTPBody?,
        metadata: OpenAPIRuntime.ServerRequestMetadata
    ) async throws -> (HTTPTypes.HTTPResponse, OpenAPIRuntime.HTTPBody?) {
        try await handle(
            request: request,
            requestBody: body,
            metadata: metadata,
            forOperation: Operations.PostRoomVoteCodeQuestionID.id,
            using: {
                APIHandler.postRoomVoteCodeQuestionID($0)
            },
            deserializer: { request, requestBody, metadata in
                let path: Operations.PostRoomVoteCodeQuestionID.Input.Path = .init(
                    code: try converter.getPathParameterAsURI(
                        in: metadata.pathParameters,
                        name: "code",
                        as: Components.Parameters.RoomCode.self
                    ),
                    questionID: try converter.getPathParameterAsURI(
                        in: metadata.pathParameters,
                        name: "questionID",
                        as: Components.Parameters.QuestionID.self
                    )
                )
                let headers: Operations.PostRoomVoteCodeQuestionID.Input.Headers = .init(participantToken: try converter.getRequiredHeaderFieldAsURI(
                    in: request.headerFields,
                    name: "Participant-Token",
                    as: Components.Parameters.ParticipantToken.self
                ))
                let contentType = converter.extractContentTypeIfPresent(in: request.headerFields)
                let body: Operations.PostRoomVoteCodeQuestionID.Input.Body
                let chosenContentType = try converter.bestContentType(
                    received: contentType,
                    options: [
                        "application/json"
                    ]
                )
                switch chosenContentType {
                case "application/json":
                    body = try await converter.getRequiredRequestBodyAsJSON(
                        Components.Schemas.AnyVote.self,
                        from: requestBody,
                        transforming: { value in
                            .json(value)
                        }
                    )
                default:
                    preconditionFailure("bestContentType chose an invalid content type.")
                }
                return Operations.PostRoomVoteCodeQuestionID.Input(
                    path: path,
                    headers: headers,
                    body: body
                )
            },
            serializer: { output, request in
                switch output {
                case let .ok(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 200)
                    suppressMutabilityWarning(&response)
                    return (response, nil)
                case let .badRequest(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 400)
                    suppressMutabilityWarning(&response)
                    return (response, nil)
                case let .forbidden(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 403)
                    suppressMutabilityWarning(&response)
                    return (response, nil)
                case let .notFound(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 404)
                    suppressMutabilityWarning(&response)
                    return (response, nil)
                case let .undocumented(statusCode, _):
                    return (.init(soar_statusCode: statusCode), nil)
                }
            }
        )
    }
    /// Check the result of the question
    ///
    /// - Remark: HTTP `GET /room/question-result/{code}/{questionID}`.
    /// - Remark: Generated from `#/paths//room/question-result/{code}/{questionID}/get`.
    func getRoomQuestionResultCodeQuestionID(
        request: HTTPTypes.HTTPRequest,
        body: OpenAPIRuntime.HTTPBody?,
        metadata: OpenAPIRuntime.ServerRequestMetadata
    ) async throws -> (HTTPTypes.HTTPResponse, OpenAPIRuntime.HTTPBody?) {
        try await handle(
            request: request,
            requestBody: body,
            metadata: metadata,
            forOperation: Operations.GetRoomQuestionResultCodeQuestionID.id,
            using: {
                APIHandler.getRoomQuestionResultCodeQuestionID($0)
            },
            deserializer: { request, requestBody, metadata in
                let path: Operations.GetRoomQuestionResultCodeQuestionID.Input.Path = .init(
                    code: try converter.getPathParameterAsURI(
                        in: metadata.pathParameters,
                        name: "code",
                        as: Components.Parameters.RoomCode.self
                    ),
                    questionID: try converter.getPathParameterAsURI(
                        in: metadata.pathParameters,
                        name: "questionID",
                        as: Components.Parameters.QuestionID.self
                    )
                )
                let headers: Operations.GetRoomQuestionResultCodeQuestionID.Input.Headers = .init(accept: try converter.extractAcceptHeaderIfPresent(in: request.headerFields))
                return Operations.GetRoomQuestionResultCodeQuestionID.Input(
                    path: path,
                    headers: headers
                )
            },
            serializer: { output, request in
                switch output {
                case let .ok(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 200)
                    suppressMutabilityWarning(&response)
                    let body: OpenAPIRuntime.HTTPBody
                    switch value.body {
                    case let .json(value):
                        try converter.validateAcceptIfPresent(
                            "application/json",
                            in: request.headerFields
                        )
                        body = try converter.setResponseBodyAsJSON(
                            value,
                            headerFields: &response.headerFields,
                            contentType: "application/json; charset=utf-8"
                        )
                    }
                    return (response, body)
                case let .badRequest(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 400)
                    suppressMutabilityWarning(&response)
                    let body: OpenAPIRuntime.HTTPBody
                    switch value.body {
                    case let .json(value):
                        try converter.validateAcceptIfPresent(
                            "application/json",
                            in: request.headerFields
                        )
                        body = try converter.setResponseBodyAsJSON(
                            value,
                            headerFields: &response.headerFields,
                            contentType: "application/json; charset=utf-8"
                        )
                    }
                    return (response, body)
                case let .notFound(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 404)
                    suppressMutabilityWarning(&response)
                    let body: OpenAPIRuntime.HTTPBody
                    switch value.body {
                    case let .json(value):
                        try converter.validateAcceptIfPresent(
                            "application/json",
                            in: request.headerFields
                        )
                        body = try converter.setResponseBodyAsJSON(
                            value,
                            headerFields: &response.headerFields,
                            contentType: "application/json; charset=utf-8"
                        )
                    }
                    return (response, body)
                case let .undocumented(statusCode, _):
                    return (.init(soar_statusCode: statusCode), nil)
                }
            }
        )
    }
    /// Get the vote count associated with a question
    ///
    /// - Remark: HTTP `GET /room/question-vote-count/{code}/{questionID}`.
    /// - Remark: Generated from `#/paths//room/question-vote-count/{code}/{questionID}/get`.
    func getRoomQuestionVoteCountCodeQuestionID(
        request: HTTPTypes.HTTPRequest,
        body: OpenAPIRuntime.HTTPBody?,
        metadata: OpenAPIRuntime.ServerRequestMetadata
    ) async throws -> (HTTPTypes.HTTPResponse, OpenAPIRuntime.HTTPBody?) {
        try await handle(
            request: request,
            requestBody: body,
            metadata: metadata,
            forOperation: Operations.GetRoomQuestionVoteCountCodeQuestionID.id,
            using: {
                APIHandler.getRoomQuestionVoteCountCodeQuestionID($0)
            },
            deserializer: { request, requestBody, metadata in
                let path: Operations.GetRoomQuestionVoteCountCodeQuestionID.Input.Path = .init(
                    code: try converter.getPathParameterAsURI(
                        in: metadata.pathParameters,
                        name: "code",
                        as: Components.Parameters.RoomCode.self
                    ),
                    questionID: try converter.getPathParameterAsURI(
                        in: metadata.pathParameters,
                        name: "questionID",
                        as: Components.Parameters.QuestionID.self
                    )
                )
                let headers: Operations.GetRoomQuestionVoteCountCodeQuestionID.Input.Headers = .init(
                    roomAdminToken: try converter.getRequiredHeaderFieldAsURI(
                        in: request.headerFields,
                        name: "Room-Admin-Token",
                        as: Components.Parameters.AdminToken.self
                    ),
                    accept: try converter.extractAcceptHeaderIfPresent(in: request.headerFields)
                )
                return Operations.GetRoomQuestionVoteCountCodeQuestionID.Input(
                    path: path,
                    headers: headers
                )
            },
            serializer: { output, request in
                switch output {
                case let .ok(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 200)
                    suppressMutabilityWarning(&response)
                    return (response, nil)
                case let .notFound(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 404)
                    suppressMutabilityWarning(&response)
                    let body: OpenAPIRuntime.HTTPBody
                    switch value.body {
                    case let .json(value):
                        try converter.validateAcceptIfPresent(
                            "application/json",
                            in: request.headerFields
                        )
                        body = try converter.setResponseBodyAsJSON(
                            value,
                            headerFields: &response.headerFields,
                            contentType: "application/json; charset=utf-8"
                        )
                    }
                    return (response, body)
                case let .undocumented(statusCode, _):
                    return (.init(soar_statusCode: statusCode), nil)
                }
            }
        )
    }
}
