// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) import OpenAPIRuntime
#if os(Linux)
@preconcurrency import struct Foundation.URL
@preconcurrency import struct Foundation.Data
@preconcurrency import struct Foundation.Date
#else
import struct Foundation.URL
import struct Foundation.Data
import struct Foundation.Date
#endif
import HTTPTypes
extension APIProtocol {
    /// Registers each operation handler with the provided transport.
    /// - Parameters:
    ///   - transport: A transport to which to register the operation handlers.
    ///   - serverURL: A URL used to determine the path prefix for registered
    ///   request handlers.
    ///   - configuration: A set of configuration values for the server.
    ///   - middlewares: A list of middlewares to call before the handler.
    public func registerHandlers(
        on transport: any ServerTransport,
        serverURL: Foundation.URL = .defaultOpenAPIServerURL,
        configuration: Configuration = .init(),
        middlewares: [any ServerMiddleware] = []
    ) throws {
        let server = UniversalServer(
            serverURL: serverURL,
            handler: self,
            configuration: configuration,
            middlewares: middlewares
        )
        try transport.register(
            {
                try await server.postRoomCreate(
                    request: $0,
                    body: $1,
                    metadata: $2
                )
            },
            method: .post,
            path: server.apiPathComponentsWithServerPrefix("/room/create")
        )
        try transport.register(
            {
                try await server.getRoomCodeInfo(
                    request: $0,
                    body: $1,
                    metadata: $2
                )
            },
            method: .get,
            path: server.apiPathComponentsWithServerPrefix("/room/{code}/info")
        )
        try transport.register(
            {
                try await server.postRoomCodeJoin(
                    request: $0,
                    body: $1,
                    metadata: $2
                )
            },
            method: .post,
            path: server.apiPathComponentsWithServerPrefix("/room/{code}/join")
        )
        try transport.register(
            {
                try await server.getRoomCodeJoinRequests(
                    request: $0,
                    body: $1,
                    metadata: $2
                )
            },
            method: .get,
            path: server.apiPathComponentsWithServerPrefix("/room/{code}/join-requests")
        )
        try transport.register(
            {
                try await server.postRoomCodeJoinRequests(
                    request: $0,
                    body: $1,
                    metadata: $2
                )
            },
            method: .post,
            path: server.apiPathComponentsWithServerPrefix("/room/{code}/join-requests")
        )
        try transport.register(
            {
                try await server.getRoomCodeQuestion(
                    request: $0,
                    body: $1,
                    metadata: $2
                )
            },
            method: .get,
            path: server.apiPathComponentsWithServerPrefix("/room/{code}/question")
        )
        try transport.register(
            {
                try await server.postRoomCodeQuestion(
                    request: $0,
                    body: $1,
                    metadata: $2
                )
            },
            method: .post,
            path: server.apiPathComponentsWithServerPrefix("/room/{code}/question")
        )
        try transport.register(
            {
                try await server.putRoomCodeQuestionID(
                    request: $0,
                    body: $1,
                    metadata: $2
                )
            },
            method: .put,
            path: server.apiPathComponentsWithServerPrefix("/room/{code}/{questionID}")
        )
        try transport.register(
            {
                try await server.deleteRoomCodeQuestionID(
                    request: $0,
                    body: $1,
                    metadata: $2
                )
            },
            method: .delete,
            path: server.apiPathComponentsWithServerPrefix("/room/{code}/{questionID}")
        )
        try transport.register(
            {
                try await server.postRoomCodeQuestionIDVote(
                    request: $0,
                    body: $1,
                    metadata: $2
                )
            },
            method: .post,
            path: server.apiPathComponentsWithServerPrefix("/room/{code}/{questionID}/vote")
        )
        try transport.register(
            {
                try await server.getRoomCodeQuestionIDResult(
                    request: $0,
                    body: $1,
                    metadata: $2
                )
            },
            method: .get,
            path: server.apiPathComponentsWithServerPrefix("/room/{code}/{questionID}/result")
        )
        try transport.register(
            {
                try await server.getRoomCodeQuestionIDVotesInfo(
                    request: $0,
                    body: $1,
                    metadata: $2
                )
            },
            method: .get,
            path: server.apiPathComponentsWithServerPrefix("/room/{code}/{questionID}/votes-info")
        )
    }
}

fileprivate extension UniversalServer where APIHandler: APIProtocol {
    /// Creates a new room
    ///
    /// Creates a new room with the given options.
    ///
    /// - Remark: HTTP `POST /room/create`.
    /// - Remark: Generated from `#/paths//room/create/post`.
    func postRoomCreate(
        request: HTTPTypes.HTTPRequest,
        body: OpenAPIRuntime.HTTPBody?,
        metadata: OpenAPIRuntime.ServerRequestMetadata
    ) async throws -> (HTTPTypes.HTTPResponse, OpenAPIRuntime.HTTPBody?) {
        try await handle(
            request: request,
            requestBody: body,
            metadata: metadata,
            forOperation: Operations.PostRoomCreate.id,
            using: {
                APIHandler.postRoomCreate($0)
            },
            deserializer: { request, requestBody, metadata in
                let headers: Operations.PostRoomCreate.Input.Headers = .init(accept: try converter.extractAcceptHeaderIfPresent(in: request.headerFields))
                let contentType = converter.extractContentTypeIfPresent(in: request.headerFields)
                let body: Operations.PostRoomCreate.Input.Body
                let chosenContentType = try converter.bestContentType(
                    received: contentType,
                    options: [
                        "application/json"
                    ]
                )
                switch chosenContentType {
                case "application/json":
                    body = try await converter.getRequiredRequestBodyAsJSON(
                        Operations.PostRoomCreate.Input.Body.JsonPayload.self,
                        from: requestBody,
                        transforming: { value in
                            .json(value)
                        }
                    )
                default:
                    preconditionFailure("bestContentType chose an invalid content type.")
                }
                return Operations.PostRoomCreate.Input(
                    headers: headers,
                    body: body
                )
            },
            serializer: { output, request in
                switch output {
                case let .ok(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 200)
                    suppressMutabilityWarning(&response)
                    let body: OpenAPIRuntime.HTTPBody
                    switch value.body {
                    case let .json(value):
                        try converter.validateAcceptIfPresent(
                            "application/json",
                            in: request.headerFields
                        )
                        body = try converter.setResponseBodyAsJSON(
                            value,
                            headerFields: &response.headerFields,
                            contentType: "application/json; charset=utf-8"
                        )
                    }
                    return (response, body)
                case let .internalServerError(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 500)
                    suppressMutabilityWarning(&response)
                    let body: OpenAPIRuntime.HTTPBody
                    switch value.body {
                    case let .json(value):
                        try converter.validateAcceptIfPresent(
                            "application/json",
                            in: request.headerFields
                        )
                        body = try converter.setResponseBodyAsJSON(
                            value,
                            headerFields: &response.headerFields,
                            contentType: "application/json; charset=utf-8"
                        )
                    }
                    return (response, body)
                case let .undocumented(statusCode, _):
                    return (.init(soar_statusCode: statusCode), nil)
                }
            }
        )
    }
    /// Get information about a room
    ///
    /// Provides information about a room, like whether the room code corresponds to a valid room
    ///
    /// - Remark: HTTP `GET /room/{code}/info`.
    /// - Remark: Generated from `#/paths//room/{code}/info/get`.
    func getRoomCodeInfo(
        request: HTTPTypes.HTTPRequest,
        body: OpenAPIRuntime.HTTPBody?,
        metadata: OpenAPIRuntime.ServerRequestMetadata
    ) async throws -> (HTTPTypes.HTTPResponse, OpenAPIRuntime.HTTPBody?) {
        try await handle(
            request: request,
            requestBody: body,
            metadata: metadata,
            forOperation: Operations.GetRoomCodeInfo.id,
            using: {
                APIHandler.getRoomCodeInfo($0)
            },
            deserializer: { request, requestBody, metadata in
                let path: Operations.GetRoomCodeInfo.Input.Path = .init(code: try converter.getPathParameterAsURI(
                    in: metadata.pathParameters,
                    name: "code",
                    as: Components.Parameters.RoomCode.self
                ))
                let headers: Operations.GetRoomCodeInfo.Input.Headers = .init(accept: try converter.extractAcceptHeaderIfPresent(in: request.headerFields))
                return Operations.GetRoomCodeInfo.Input(
                    path: path,
                    headers: headers
                )
            },
            serializer: { output, request in
                switch output {
                case let .ok(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 200)
                    suppressMutabilityWarning(&response)
                    let body: OpenAPIRuntime.HTTPBody
                    switch value.body {
                    case let .json(value):
                        try converter.validateAcceptIfPresent(
                            "application/json",
                            in: request.headerFields
                        )
                        body = try converter.setResponseBodyAsJSON(
                            value,
                            headerFields: &response.headerFields,
                            contentType: "application/json; charset=utf-8"
                        )
                    }
                    return (response, body)
                case let .notFound(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 404)
                    suppressMutabilityWarning(&response)
                    return (response, nil)
                case let .undocumented(statusCode, _):
                    return (.init(soar_statusCode: statusCode), nil)
                }
            }
        )
    }
    /// Join a room
    ///
    /// This route only asks the room owner whether to allow you to join the room, it doesn't actually open a connection to the room. To do that, use the `/room/connect/{code}` route.
    ///
    /// - Remark: HTTP `POST /room/{code}/join`.
    /// - Remark: Generated from `#/paths//room/{code}/join/post`.
    func postRoomCodeJoin(
        request: HTTPTypes.HTTPRequest,
        body: OpenAPIRuntime.HTTPBody?,
        metadata: OpenAPIRuntime.ServerRequestMetadata
    ) async throws -> (HTTPTypes.HTTPResponse, OpenAPIRuntime.HTTPBody?) {
        try await handle(
            request: request,
            requestBody: body,
            metadata: metadata,
            forOperation: Operations.PostRoomCodeJoin.id,
            using: {
                APIHandler.postRoomCodeJoin($0)
            },
            deserializer: { request, requestBody, metadata in
                let path: Operations.PostRoomCodeJoin.Input.Path = .init(code: try converter.getPathParameterAsURI(
                    in: metadata.pathParameters,
                    name: "code",
                    as: Components.Parameters.RoomCode.self
                ))
                let headers: Operations.PostRoomCodeJoin.Input.Headers = .init(accept: try converter.extractAcceptHeaderIfPresent(in: request.headerFields))
                let contentType = converter.extractContentTypeIfPresent(in: request.headerFields)
                let body: Operations.PostRoomCodeJoin.Input.Body
                let chosenContentType = try converter.bestContentType(
                    received: contentType,
                    options: [
                        "application/json"
                    ]
                )
                switch chosenContentType {
                case "application/json":
                    body = try await converter.getRequiredRequestBodyAsJSON(
                        Operations.PostRoomCodeJoin.Input.Body.JsonPayload.self,
                        from: requestBody,
                        transforming: { value in
                            .json(value)
                        }
                    )
                default:
                    preconditionFailure("bestContentType chose an invalid content type.")
                }
                return Operations.PostRoomCodeJoin.Input(
                    path: path,
                    headers: headers,
                    body: body
                )
            },
            serializer: { output, request in
                switch output {
                case let .ok(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 200)
                    suppressMutabilityWarning(&response)
                    let body: OpenAPIRuntime.HTTPBody
                    switch value.body {
                    case let .json(value):
                        try converter.validateAcceptIfPresent(
                            "application/json",
                            in: request.headerFields
                        )
                        body = try converter.setResponseBodyAsJSON(
                            value,
                            headerFields: &response.headerFields,
                            contentType: "application/json; charset=utf-8"
                        )
                    }
                    return (response, body)
                case let .forbidden(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 403)
                    suppressMutabilityWarning(&response)
                    return (response, nil)
                case let .notFound(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 404)
                    suppressMutabilityWarning(&response)
                    return (response, nil)
                case let .undocumented(statusCode, _):
                    return (.init(soar_statusCode: statusCode), nil)
                }
            }
        )
    }
    /// Pending requests to join a room
    ///
    /// Allows an admin to view pending join requests for a room
    ///
    /// - Remark: HTTP `GET /room/{code}/join-requests`.
    /// - Remark: Generated from `#/paths//room/{code}/join-requests/get`.
    func getRoomCodeJoinRequests(
        request: HTTPTypes.HTTPRequest,
        body: OpenAPIRuntime.HTTPBody?,
        metadata: OpenAPIRuntime.ServerRequestMetadata
    ) async throws -> (HTTPTypes.HTTPResponse, OpenAPIRuntime.HTTPBody?) {
        try await handle(
            request: request,
            requestBody: body,
            metadata: metadata,
            forOperation: Operations.GetRoomCodeJoinRequests.id,
            using: {
                APIHandler.getRoomCodeJoinRequests($0)
            },
            deserializer: { request, requestBody, metadata in
                let path: Operations.GetRoomCodeJoinRequests.Input.Path = .init(code: try converter.getPathParameterAsURI(
                    in: metadata.pathParameters,
                    name: "code",
                    as: Components.Parameters.RoomCode.self
                ))
                let headers: Operations.GetRoomCodeJoinRequests.Input.Headers = .init(
                    roomAdminToken: try converter.getRequiredHeaderFieldAsURI(
                        in: request.headerFields,
                        name: "Room-Admin-Token",
                        as: Components.Parameters.AdminToken.self
                    ),
                    accept: try converter.extractAcceptHeaderIfPresent(in: request.headerFields)
                )
                return Operations.GetRoomCodeJoinRequests.Input(
                    path: path,
                    headers: headers
                )
            },
            serializer: { output, request in
                switch output {
                case let .ok(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 200)
                    suppressMutabilityWarning(&response)
                    let body: OpenAPIRuntime.HTTPBody
                    switch value.body {
                    case let .json(value):
                        try converter.validateAcceptIfPresent(
                            "application/json",
                            in: request.headerFields
                        )
                        body = try converter.setResponseBodyAsJSON(
                            value,
                            headerFields: &response.headerFields,
                            contentType: "application/json; charset=utf-8"
                        )
                    }
                    return (response, body)
                case let .forbidden(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 403)
                    suppressMutabilityWarning(&response)
                    return (response, nil)
                case let .notFound(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 404)
                    suppressMutabilityWarning(&response)
                    return (response, nil)
                case let .undocumented(statusCode, _):
                    return (.init(soar_statusCode: statusCode), nil)
                }
            }
        )
    }
    /// Handle join requests
    ///
    /// Allows a room admin to accept or reject join requests.
    ///
    /// - Remark: HTTP `POST /room/{code}/join-requests`.
    /// - Remark: Generated from `#/paths//room/{code}/join-requests/post`.
    func postRoomCodeJoinRequests(
        request: HTTPTypes.HTTPRequest,
        body: OpenAPIRuntime.HTTPBody?,
        metadata: OpenAPIRuntime.ServerRequestMetadata
    ) async throws -> (HTTPTypes.HTTPResponse, OpenAPIRuntime.HTTPBody?) {
        try await handle(
            request: request,
            requestBody: body,
            metadata: metadata,
            forOperation: Operations.PostRoomCodeJoinRequests.id,
            using: {
                APIHandler.postRoomCodeJoinRequests($0)
            },
            deserializer: { request, requestBody, metadata in
                let path: Operations.PostRoomCodeJoinRequests.Input.Path = .init(code: try converter.getPathParameterAsURI(
                    in: metadata.pathParameters,
                    name: "code",
                    as: Components.Parameters.RoomCode.self
                ))
                let headers: Operations.PostRoomCodeJoinRequests.Input.Headers = .init(
                    roomAdminToken: try converter.getRequiredHeaderFieldAsURI(
                        in: request.headerFields,
                        name: "Room-Admin-Token",
                        as: Components.Parameters.AdminToken.self
                    ),
                    accept: try converter.extractAcceptHeaderIfPresent(in: request.headerFields)
                )
                let contentType = converter.extractContentTypeIfPresent(in: request.headerFields)
                let body: Operations.PostRoomCodeJoinRequests.Input.Body
                let chosenContentType = try converter.bestContentType(
                    received: contentType,
                    options: [
                        "application/json"
                    ]
                )
                switch chosenContentType {
                case "application/json":
                    body = try await converter.getRequiredRequestBodyAsJSON(
                        Operations.PostRoomCodeJoinRequests.Input.Body.JsonPayload.self,
                        from: requestBody,
                        transforming: { value in
                            .json(value)
                        }
                    )
                default:
                    preconditionFailure("bestContentType chose an invalid content type.")
                }
                return Operations.PostRoomCodeJoinRequests.Input(
                    path: path,
                    headers: headers,
                    body: body
                )
            },
            serializer: { output, request in
                switch output {
                case let .ok(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 200)
                    suppressMutabilityWarning(&response)
                    let body: OpenAPIRuntime.HTTPBody
                    switch value.body {
                    case let .json(value):
                        try converter.validateAcceptIfPresent(
                            "application/json",
                            in: request.headerFields
                        )
                        body = try converter.setResponseBodyAsJSON(
                            value,
                            headerFields: &response.headerFields,
                            contentType: "application/json; charset=utf-8"
                        )
                    }
                    return (response, body)
                case let .badRequest(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 400)
                    suppressMutabilityWarning(&response)
                    let body: OpenAPIRuntime.HTTPBody
                    switch value.body {
                    case let .json(value):
                        try converter.validateAcceptIfPresent(
                            "application/json",
                            in: request.headerFields
                        )
                        body = try converter.setResponseBodyAsJSON(
                            value,
                            headerFields: &response.headerFields,
                            contentType: "application/json; charset=utf-8"
                        )
                    }
                    return (response, body)
                case let .forbidden(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 403)
                    suppressMutabilityWarning(&response)
                    return (response, nil)
                case let .notFound(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 404)
                    suppressMutabilityWarning(&response)
                    return (response, nil)
                case let .undocumented(statusCode, _):
                    return (.init(soar_statusCode: statusCode), nil)
                }
            }
        )
    }
    /// Get the active question
    ///
    /// - Remark: HTTP `GET /room/{code}/question`.
    /// - Remark: Generated from `#/paths//room/{code}/question/get`.
    func getRoomCodeQuestion(
        request: HTTPTypes.HTTPRequest,
        body: OpenAPIRuntime.HTTPBody?,
        metadata: OpenAPIRuntime.ServerRequestMetadata
    ) async throws -> (HTTPTypes.HTTPResponse, OpenAPIRuntime.HTTPBody?) {
        try await handle(
            request: request,
            requestBody: body,
            metadata: metadata,
            forOperation: Operations.GetRoomCodeQuestion.id,
            using: {
                APIHandler.getRoomCodeQuestion($0)
            },
            deserializer: { request, requestBody, metadata in
                let path: Operations.GetRoomCodeQuestion.Input.Path = .init(code: try converter.getPathParameterAsURI(
                    in: metadata.pathParameters,
                    name: "code",
                    as: Components.Parameters.RoomCode.self
                ))
                let headers: Operations.GetRoomCodeQuestion.Input.Headers = .init(accept: try converter.extractAcceptHeaderIfPresent(in: request.headerFields))
                return Operations.GetRoomCodeQuestion.Input(
                    path: path,
                    headers: headers
                )
            },
            serializer: { output, request in
                switch output {
                case let .ok(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 200)
                    suppressMutabilityWarning(&response)
                    let body: OpenAPIRuntime.HTTPBody
                    switch value.body {
                    case let .json(value):
                        try converter.validateAcceptIfPresent(
                            "application/json",
                            in: request.headerFields
                        )
                        body = try converter.setResponseBodyAsJSON(
                            value,
                            headerFields: &response.headerFields,
                            contentType: "application/json; charset=utf-8"
                        )
                    }
                    return (response, body)
                case let .badRequest(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 400)
                    suppressMutabilityWarning(&response)
                    return (response, nil)
                case let .notFound(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 404)
                    suppressMutabilityWarning(&response)
                    return (response, nil)
                case let .undocumented(statusCode, _):
                    return (.init(soar_statusCode: statusCode), nil)
                }
            }
        )
    }
    /// Submit a new question
    ///
    /// - Remark: HTTP `POST /room/{code}/question`.
    /// - Remark: Generated from `#/paths//room/{code}/question/post`.
    func postRoomCodeQuestion(
        request: HTTPTypes.HTTPRequest,
        body: OpenAPIRuntime.HTTPBody?,
        metadata: OpenAPIRuntime.ServerRequestMetadata
    ) async throws -> (HTTPTypes.HTTPResponse, OpenAPIRuntime.HTTPBody?) {
        try await handle(
            request: request,
            requestBody: body,
            metadata: metadata,
            forOperation: Operations.PostRoomCodeQuestion.id,
            using: {
                APIHandler.postRoomCodeQuestion($0)
            },
            deserializer: { request, requestBody, metadata in
                let path: Operations.PostRoomCodeQuestion.Input.Path = .init(code: try converter.getPathParameterAsURI(
                    in: metadata.pathParameters,
                    name: "code",
                    as: Components.Parameters.RoomCode.self
                ))
                let headers: Operations.PostRoomCodeQuestion.Input.Headers = .init(
                    roomAdminToken: try converter.getRequiredHeaderFieldAsURI(
                        in: request.headerFields,
                        name: "Room-Admin-Token",
                        as: Components.Parameters.AdminToken.self
                    ),
                    accept: try converter.extractAcceptHeaderIfPresent(in: request.headerFields)
                )
                let contentType = converter.extractContentTypeIfPresent(in: request.headerFields)
                let body: Operations.PostRoomCodeQuestion.Input.Body
                let chosenContentType = try converter.bestContentType(
                    received: contentType,
                    options: [
                        "application/json"
                    ]
                )
                switch chosenContentType {
                case "application/json":
                    body = try await converter.getRequiredRequestBodyAsJSON(
                        Components.Schemas.QuestionCreateRequest.self,
                        from: requestBody,
                        transforming: { value in
                            .json(value)
                        }
                    )
                default:
                    preconditionFailure("bestContentType chose an invalid content type.")
                }
                return Operations.PostRoomCodeQuestion.Input(
                    path: path,
                    headers: headers,
                    body: body
                )
            },
            serializer: { output, request in
                switch output {
                case let .ok(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 200)
                    suppressMutabilityWarning(&response)
                    let body: OpenAPIRuntime.HTTPBody
                    switch value.body {
                    case let .json(value):
                        try converter.validateAcceptIfPresent(
                            "application/json",
                            in: request.headerFields
                        )
                        body = try converter.setResponseBodyAsJSON(
                            value,
                            headerFields: &response.headerFields,
                            contentType: "application/json; charset=utf-8"
                        )
                    }
                    return (response, body)
                case let .badRequest(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 400)
                    suppressMutabilityWarning(&response)
                    let body: OpenAPIRuntime.HTTPBody
                    switch value.body {
                    case let .json(value):
                        try converter.validateAcceptIfPresent(
                            "application/json",
                            in: request.headerFields
                        )
                        body = try converter.setResponseBodyAsJSON(
                            value,
                            headerFields: &response.headerFields,
                            contentType: "application/json; charset=utf-8"
                        )
                    }
                    return (response, body)
                case let .forbidden(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 403)
                    suppressMutabilityWarning(&response)
                    return (response, nil)
                case let .notFound(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 404)
                    suppressMutabilityWarning(&response)
                    return (response, nil)
                case let .internalServerError(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 500)
                    suppressMutabilityWarning(&response)
                    let body: OpenAPIRuntime.HTTPBody
                    switch value.body {
                    case let .json(value):
                        try converter.validateAcceptIfPresent(
                            "application/json",
                            in: request.headerFields
                        )
                        body = try converter.setResponseBodyAsJSON(
                            value,
                            headerFields: &response.headerFields,
                            contentType: "application/json; charset=utf-8"
                        )
                    }
                    return (response, body)
                case let .undocumented(statusCode, _):
                    return (.init(soar_statusCode: statusCode), nil)
                }
            }
        )
    }
    /// Edits the current question
    ///
    /// Modify attributes of the current question
    ///
    /// - Remark: HTTP `PUT /room/{code}/{questionID}`.
    /// - Remark: Generated from `#/paths//room/{code}/{questionID}/put`.
    func putRoomCodeQuestionID(
        request: HTTPTypes.HTTPRequest,
        body: OpenAPIRuntime.HTTPBody?,
        metadata: OpenAPIRuntime.ServerRequestMetadata
    ) async throws -> (HTTPTypes.HTTPResponse, OpenAPIRuntime.HTTPBody?) {
        try await handle(
            request: request,
            requestBody: body,
            metadata: metadata,
            forOperation: Operations.PutRoomCodeQuestionID.id,
            using: {
                APIHandler.putRoomCodeQuestionID($0)
            },
            deserializer: { request, requestBody, metadata in
                let path: Operations.PutRoomCodeQuestionID.Input.Path = .init(
                    code: try converter.getPathParameterAsURI(
                        in: metadata.pathParameters,
                        name: "code",
                        as: Components.Parameters.RoomCode.self
                    ),
                    questionID: try converter.getPathParameterAsURI(
                        in: metadata.pathParameters,
                        name: "questionID",
                        as: Components.Parameters.QuestionID.self
                    )
                )
                let headers: Operations.PutRoomCodeQuestionID.Input.Headers = .init(roomAdminToken: try converter.getRequiredHeaderFieldAsURI(
                    in: request.headerFields,
                    name: "Room-Admin-Token",
                    as: Components.Parameters.AdminToken.self
                ))
                let contentType = converter.extractContentTypeIfPresent(in: request.headerFields)
                let body: Operations.PutRoomCodeQuestionID.Input.Body
                let chosenContentType = try converter.bestContentType(
                    received: contentType,
                    options: [
                        "application/json"
                    ]
                )
                switch chosenContentType {
                case "application/json":
                    body = try await converter.getRequiredRequestBodyAsJSON(
                        Components.Schemas.QuestionModifyRequest.self,
                        from: requestBody,
                        transforming: { value in
                            .json(value)
                        }
                    )
                default:
                    preconditionFailure("bestContentType chose an invalid content type.")
                }
                return Operations.PutRoomCodeQuestionID.Input(
                    path: path,
                    headers: headers,
                    body: body
                )
            },
            serializer: { output, request in
                switch output {
                case let .ok(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 200)
                    suppressMutabilityWarning(&response)
                    return (response, nil)
                case let .badRequest(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 400)
                    suppressMutabilityWarning(&response)
                    return (response, nil)
                case let .forbidden(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 403)
                    suppressMutabilityWarning(&response)
                    return (response, nil)
                case let .notFound(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 404)
                    suppressMutabilityWarning(&response)
                    return (response, nil)
                case let .undocumented(statusCode, _):
                    return (.init(soar_statusCode: statusCode), nil)
                }
            }
        )
    }
    /// Removes the current question
    ///
    /// - Remark: HTTP `DELETE /room/{code}/{questionID}`.
    /// - Remark: Generated from `#/paths//room/{code}/{questionID}/delete`.
    func deleteRoomCodeQuestionID(
        request: HTTPTypes.HTTPRequest,
        body: OpenAPIRuntime.HTTPBody?,
        metadata: OpenAPIRuntime.ServerRequestMetadata
    ) async throws -> (HTTPTypes.HTTPResponse, OpenAPIRuntime.HTTPBody?) {
        try await handle(
            request: request,
            requestBody: body,
            metadata: metadata,
            forOperation: Operations.DeleteRoomCodeQuestionID.id,
            using: {
                APIHandler.deleteRoomCodeQuestionID($0)
            },
            deserializer: { request, requestBody, metadata in
                let path: Operations.DeleteRoomCodeQuestionID.Input.Path = .init(
                    code: try converter.getPathParameterAsURI(
                        in: metadata.pathParameters,
                        name: "code",
                        as: Components.Parameters.RoomCode.self
                    ),
                    questionID: try converter.getPathParameterAsURI(
                        in: metadata.pathParameters,
                        name: "questionID",
                        as: Components.Parameters.QuestionID.self
                    )
                )
                let headers: Operations.DeleteRoomCodeQuestionID.Input.Headers = .init(
                    roomAdminToken: try converter.getRequiredHeaderFieldAsURI(
                        in: request.headerFields,
                        name: "Room-Admin-Token",
                        as: Components.Parameters.AdminToken.self
                    ),
                    accept: try converter.extractAcceptHeaderIfPresent(in: request.headerFields)
                )
                return Operations.DeleteRoomCodeQuestionID.Input(
                    path: path,
                    headers: headers
                )
            },
            serializer: { output, request in
                switch output {
                case let .ok(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 200)
                    suppressMutabilityWarning(&response)
                    let body: OpenAPIRuntime.HTTPBody
                    switch value.body {
                    case let .json(value):
                        try converter.validateAcceptIfPresent(
                            "application/json",
                            in: request.headerFields
                        )
                        body = try converter.setResponseBodyAsJSON(
                            value,
                            headerFields: &response.headerFields,
                            contentType: "application/json; charset=utf-8"
                        )
                    }
                    return (response, body)
                case let .badRequest(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 400)
                    suppressMutabilityWarning(&response)
                    return (response, nil)
                case let .forbidden(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 403)
                    suppressMutabilityWarning(&response)
                    return (response, nil)
                case let .notFound(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 404)
                    suppressMutabilityWarning(&response)
                    return (response, nil)
                case let .undocumented(statusCode, _):
                    return (.init(soar_statusCode: statusCode), nil)
                }
            }
        )
    }
    /// Vote on a question
    ///
    /// - Remark: HTTP `POST /room/{code}/{questionID}/vote`.
    /// - Remark: Generated from `#/paths//room/{code}/{questionID}/vote/post`.
    func postRoomCodeQuestionIDVote(
        request: HTTPTypes.HTTPRequest,
        body: OpenAPIRuntime.HTTPBody?,
        metadata: OpenAPIRuntime.ServerRequestMetadata
    ) async throws -> (HTTPTypes.HTTPResponse, OpenAPIRuntime.HTTPBody?) {
        try await handle(
            request: request,
            requestBody: body,
            metadata: metadata,
            forOperation: Operations.PostRoomCodeQuestionIDVote.id,
            using: {
                APIHandler.postRoomCodeQuestionIDVote($0)
            },
            deserializer: { request, requestBody, metadata in
                let path: Operations.PostRoomCodeQuestionIDVote.Input.Path = .init(
                    code: try converter.getPathParameterAsURI(
                        in: metadata.pathParameters,
                        name: "code",
                        as: Components.Parameters.RoomCode.self
                    ),
                    questionID: try converter.getPathParameterAsURI(
                        in: metadata.pathParameters,
                        name: "questionID",
                        as: Components.Parameters.QuestionID.self
                    )
                )
                let headers: Operations.PostRoomCodeQuestionIDVote.Input.Headers = .init(participantToken: try converter.getRequiredHeaderFieldAsURI(
                    in: request.headerFields,
                    name: "Participant-Token",
                    as: Components.Parameters.ParticipantToken.self
                ))
                let contentType = converter.extractContentTypeIfPresent(in: request.headerFields)
                let body: Operations.PostRoomCodeQuestionIDVote.Input.Body
                let chosenContentType = try converter.bestContentType(
                    received: contentType,
                    options: [
                        "application/json"
                    ]
                )
                switch chosenContentType {
                case "application/json":
                    body = try await converter.getRequiredRequestBodyAsJSON(
                        Components.Schemas.AnyVote.self,
                        from: requestBody,
                        transforming: { value in
                            .json(value)
                        }
                    )
                default:
                    preconditionFailure("bestContentType chose an invalid content type.")
                }
                return Operations.PostRoomCodeQuestionIDVote.Input(
                    path: path,
                    headers: headers,
                    body: body
                )
            },
            serializer: { output, request in
                switch output {
                case let .ok(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 200)
                    suppressMutabilityWarning(&response)
                    return (response, nil)
                case let .badRequest(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 400)
                    suppressMutabilityWarning(&response)
                    return (response, nil)
                case let .forbidden(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 403)
                    suppressMutabilityWarning(&response)
                    return (response, nil)
                case let .notFound(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 404)
                    suppressMutabilityWarning(&response)
                    return (response, nil)
                case let .undocumented(statusCode, _):
                    return (.init(soar_statusCode: statusCode), nil)
                }
            }
        )
    }
    /// Check the result of the question
    ///
    /// - Remark: HTTP `GET /room/{code}/{questionID}/result`.
    /// - Remark: Generated from `#/paths//room/{code}/{questionID}/result/get`.
    func getRoomCodeQuestionIDResult(
        request: HTTPTypes.HTTPRequest,
        body: OpenAPIRuntime.HTTPBody?,
        metadata: OpenAPIRuntime.ServerRequestMetadata
    ) async throws -> (HTTPTypes.HTTPResponse, OpenAPIRuntime.HTTPBody?) {
        try await handle(
            request: request,
            requestBody: body,
            metadata: metadata,
            forOperation: Operations.GetRoomCodeQuestionIDResult.id,
            using: {
                APIHandler.getRoomCodeQuestionIDResult($0)
            },
            deserializer: { request, requestBody, metadata in
                let path: Operations.GetRoomCodeQuestionIDResult.Input.Path = .init(
                    code: try converter.getPathParameterAsURI(
                        in: metadata.pathParameters,
                        name: "code",
                        as: Components.Parameters.RoomCode.self
                    ),
                    questionID: try converter.getPathParameterAsURI(
                        in: metadata.pathParameters,
                        name: "questionID",
                        as: Components.Parameters.QuestionID.self
                    )
                )
                let headers: Operations.GetRoomCodeQuestionIDResult.Input.Headers = .init(accept: try converter.extractAcceptHeaderIfPresent(in: request.headerFields))
                return Operations.GetRoomCodeQuestionIDResult.Input(
                    path: path,
                    headers: headers
                )
            },
            serializer: { output, request in
                switch output {
                case let .ok(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 200)
                    suppressMutabilityWarning(&response)
                    let body: OpenAPIRuntime.HTTPBody
                    switch value.body {
                    case let .json(value):
                        try converter.validateAcceptIfPresent(
                            "application/json",
                            in: request.headerFields
                        )
                        body = try converter.setResponseBodyAsJSON(
                            value,
                            headerFields: &response.headerFields,
                            contentType: "application/json; charset=utf-8"
                        )
                    }
                    return (response, body)
                case let .badRequest(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 400)
                    suppressMutabilityWarning(&response)
                    let body: OpenAPIRuntime.HTTPBody
                    switch value.body {
                    case let .json(value):
                        try converter.validateAcceptIfPresent(
                            "application/json",
                            in: request.headerFields
                        )
                        body = try converter.setResponseBodyAsJSON(
                            value,
                            headerFields: &response.headerFields,
                            contentType: "application/json; charset=utf-8"
                        )
                    }
                    return (response, body)
                case let .notFound(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 404)
                    suppressMutabilityWarning(&response)
                    let body: OpenAPIRuntime.HTTPBody
                    switch value.body {
                    case let .json(value):
                        try converter.validateAcceptIfPresent(
                            "application/json",
                            in: request.headerFields
                        )
                        body = try converter.setResponseBodyAsJSON(
                            value,
                            headerFields: &response.headerFields,
                            contentType: "application/json; charset=utf-8"
                        )
                    }
                    return (response, body)
                case let .undocumented(statusCode, _):
                    return (.init(soar_statusCode: statusCode), nil)
                }
            }
        )
    }
    /// Get the vote-information
    ///
    /// This information is limited intentionally to prevent spoiling the vote.
    ///
    /// - Remark: HTTP `GET /room/{code}/{questionID}/votes-info`.
    /// - Remark: Generated from `#/paths//room/{code}/{questionID}/votes-info/get`.
    func getRoomCodeQuestionIDVotesInfo(
        request: HTTPTypes.HTTPRequest,
        body: OpenAPIRuntime.HTTPBody?,
        metadata: OpenAPIRuntime.ServerRequestMetadata
    ) async throws -> (HTTPTypes.HTTPResponse, OpenAPIRuntime.HTTPBody?) {
        try await handle(
            request: request,
            requestBody: body,
            metadata: metadata,
            forOperation: Operations.GetRoomCodeQuestionIDVotesInfo.id,
            using: {
                APIHandler.getRoomCodeQuestionIDVotesInfo($0)
            },
            deserializer: { request, requestBody, metadata in
                let path: Operations.GetRoomCodeQuestionIDVotesInfo.Input.Path = .init(
                    code: try converter.getPathParameterAsURI(
                        in: metadata.pathParameters,
                        name: "code",
                        as: Components.Parameters.RoomCode.self
                    ),
                    questionID: try converter.getPathParameterAsURI(
                        in: metadata.pathParameters,
                        name: "questionID",
                        as: Components.Parameters.QuestionID.self
                    )
                )
                let headers: Operations.GetRoomCodeQuestionIDVotesInfo.Input.Headers = .init(
                    roomAdminToken: try converter.getRequiredHeaderFieldAsURI(
                        in: request.headerFields,
                        name: "Room-Admin-Token",
                        as: Components.Parameters.AdminToken.self
                    ),
                    accept: try converter.extractAcceptHeaderIfPresent(in: request.headerFields)
                )
                return Operations.GetRoomCodeQuestionIDVotesInfo.Input(
                    path: path,
                    headers: headers
                )
            },
            serializer: { output, request in
                switch output {
                case let .ok(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 200)
                    suppressMutabilityWarning(&response)
                    let body: OpenAPIRuntime.HTTPBody
                    switch value.body {
                    case let .json(value):
                        try converter.validateAcceptIfPresent(
                            "application/json",
                            in: request.headerFields
                        )
                        body = try converter.setResponseBodyAsJSON(
                            value,
                            headerFields: &response.headerFields,
                            contentType: "application/json; charset=utf-8"
                        )
                    }
                    return (response, body)
                case let .forbidden(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 403)
                    suppressMutabilityWarning(&response)
                    let body: OpenAPIRuntime.HTTPBody
                    switch value.body {
                    case let .json(value):
                        try converter.validateAcceptIfPresent(
                            "application/json",
                            in: request.headerFields
                        )
                        body = try converter.setResponseBodyAsJSON(
                            value,
                            headerFields: &response.headerFields,
                            contentType: "application/json; charset=utf-8"
                        )
                    }
                    return (response, body)
                case let .notFound(value):
                    suppressUnusedWarning(value)
                    var response = HTTPTypes.HTTPResponse(soar_statusCode: 404)
                    suppressMutabilityWarning(&response)
                    let body: OpenAPIRuntime.HTTPBody
                    switch value.body {
                    case let .json(value):
                        try converter.validateAcceptIfPresent(
                            "application/json",
                            in: request.headerFields
                        )
                        body = try converter.setResponseBodyAsJSON(
                            value,
                            headerFields: &response.headerFields,
                            contentType: "application/json; charset=utf-8"
                        )
                    }
                    return (response, body)
                case let .undocumented(statusCode, _):
                    return (.init(soar_statusCode: statusCode), nil)
                }
            }
        )
    }
}
