#! /bin/sh

# Make sure this script is executing from the repo folder
cd "$(dirname "$0")"

# Make the docs folder if it doesnt exist
mkdir docs

# First copy the specification
echo "Preparing Specification..."
cd specification
./update-specification

# Then build server documentation
echo "Preparing Server Documentation..." 
cd ../sock-vote-server
./generate-documentation

# Copy output into gh-pages
git checkout gh-pages
git checkout main -- ./docs
git add ./docs
git commit -m "Update docs $(date)"
git checkout main
