#! /bin/sh

cd $(dirname $0)

msys_no_pathconv_old=${MSYS_NO_PATHCONV}
export MSYS_NO_PATHCONV=1

docker run \
    --rm \
    --volume $(pwd):/src \
    --volume $(pwd)/../specification:/specification \
    --workdir /src \
    swift:6.2 \
    bash -c " \
        cd ..; \
        cp -r src container; \
        cd container; \
        swift package clean; \
        swift test; \
    "

export MSYS_NO_PATHCONV=${msys_no_pathconv_old}